name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies on root
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Configure Git User
        run: |
          git config --global user.name "Inferable CI"
          git config --global user.email "ci@inferable.ai"

      - name: Release It
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npx release-it --npm.skipChecks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
